---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moduloescritura
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moduloescritura
  template:
    metadata:
      labels:
        app: moduloescritura
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: moduloescritura
          image: crmutantes.azurecr.io/moduloescritura:v3
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 8080
          env:
            - name: moduloescritura
              value: "moduloescritura"
          livenessProbe:
            httpGet:
              path: /mutantchecker/health
              port: 8080
            initialDelaySeconds: 300
            periodSeconds: 4
            timeoutSeconds: 5
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: [ "sleep", "90" ]
          readinessProbe:
            httpGet:
              path: /mutantchecker/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: moduloescritura
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: moduloescritura